version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pylint  # Add this line

  pre_build:
    commands:
      - echo "Running Pylint for Code Quality..."
      - pylint --fail-under=5 $(find . -name "*.py")


  build:
    commands:
      - echo "Building Docker Image..."
      - docker build -t akhilakandadi/restaurant-complaints:latest .

  post_build:
    commands:
      - echo "Pushing Image to Docker Hub..."
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker push akhilakandadi/restaurant-complaints:latest
      - echo "Running Trivy Security Scan..."
      - docker run --rm aquasec/trivy image akhilakandadi/restaurant-complaints:latest
      - echo "Deploying Container..."
      - docker run -d --name cont1 -p 3000:3000 akhilakandadi/restaurant-complaints:latest

artifacts:
  files: "**/*"
