# Generated by Django 5.1.6 on 2025-02-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('FO', 'Food'), ('SV', 'Service'), ('CL', 'Cleanliness')], max_length=2)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
