# Generated by Django 5.1.6 on 2025-02-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('RE', 'Resolved'), ('IP', 'In Progress')], default='PE', max_length=2),
        ),
    ]
